name: Deploy
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*
jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        nodejs: [20.x]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
      - name: Install Node ${{ matrix.nodejs }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint code
        run: pnpm run lint
      - name: Check code
        run: pnpm run check
        env: &env
          ALLOWED_REQUEST_METHODS: GET,HEAD,POST
          CSRF_SKIP_ROUTES: /handlers/verify-csrf-token/ignore,/handlers/verify-csrf-token.json/ignore
          SECRET_KEY: J9oyuTDuGSQhwE3lOutjUgXe4yfpWQtI # 32 bytes
          SESSION_KEY: _kitty-session
  tests__unit:
    needs: checks
    strategy:
      fail-fast: false
      matrix:
        nodejs: [20.x, latest]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm run test:unit
  tests__e2e:
    needs: tests__unit
    strategy:
      fail-fast: false
      matrix:
        nodejs: [20.x]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install browsers
        run: npx playwright install --with-deps --only-shell
      - name: Run tests
        run: pnpm run test:e2e
        env:
          <<: *env
  publish:
    needs: tests__e2e
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm run package
      - name: Publish package
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
