name: Test
on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'src/lib/**'
      - 'tests/**'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/test.yml'
      - 'src/lib/**'
      - 'tests/**'
jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        nodejs: [20.x]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Node ${{ matrix.nodejs }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Check code
        run: npm run check
        env: &env
          ALLOWED_REQUEST_METHODS: GET,HEAD,POST
          CSRF_SKIP_ROUTES: /handlers/verify-csrf-token/ignore,/handlers/verify-csrf-token.json/ignore
          SECRET_KEY: J9oyuTDuGSQhwE3lOutjUgXe4yfpWQtI # 32 bytes
          SESSION_KEY: _kitty-session
  tests__unit:
    strategy:
      fail-fast: false
      matrix:
        nodejs: [20.x, latest]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
  tests__e2e:
    strategy:
      fail-fast: false
      matrix:
        nodejs: [20.x]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps --only-shell
      - name: Run tests
        run: npm run test:e2e
        env:
          <<: *env
